apiVersion: v1
appVersion: @project.version@
name: bumbershoot
description: A Helm chart installing bumbershoot - a continous deployment solution for umbrella charts
version: @project.version@
home: https://gitlab.device-insight.com/sfl/bumbershoot
maintainers:
  - name: Simon Flandergan
    url: https://github.com/deviceinsight/bumbershoot

