---
replicaCount: 1
deployment:
  image:
    repository: "deviceinsight"
    pullPolicy: IfNotPresent
  replicaCount: 1
  singletonPerNode: true
  ## resources required by the application
  resources:
    requests:
      cpu: 200m
      memory: 150Mi
    limits:
      memory: 300Mi
  javaOptions: -Xms128m -Xmx256m

probes:
  ## probes.readinessProbe for the application. This is directly expanded into the deployment chart
  readinessProbe:
    tcpSocket:
        port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 1
  ## probes.livenessProbe for the application. This is directly expanded into the deployment chart
  livenessProbe:
    tcpSocket:
        port: 8080
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3

logging:
  level:
    com.deviceinsight.bumbershoot: DEBUG

managedCharts: []
#  - name: umbrella-chart
#    defaultUpgradePolicy: MINOR
#    upgradePolicies:
#      ng-platform: NEVER
#    repository:
#      url: https://charts.sample
#      type: chartmuseum

resources: {}

nodeSelector: {}

################
# dependencies #
################
swift:
  nameOverride: swift-tiller-proxy
  enableAnalytics: false

###########
# globals #
###########

global: {}